### ISSUE TITLE
Expose quest (chain) meta data

### ISSUE THREAD

**Issue by davort** [quest-chains/mono-repo#31]
Metadata to be displayed in the UI for a quest chain and quest 👇 
Note: All of the metadata listed below is already exposed by the subgraph.

## Quest chain

1. Title
2. Description
3. Network
4. Members
5. Creator
6. Date of creation
7. Number of quests
8. Number of players
9. History of edits (with editor)

## Quest

1. Title
2. Description
3. Creator
4. Date of creation
5. Number of players
6. History of edits (with editor)

**Comment by davort** [comment]
@dan13ram @vidvidvid - what do you think about the metadata proposed above? Anything to add or remove from the lists?

**Comment by dan13ram** [comment]
@davort all of this info is already available and exposed :D

I've also added some more info. Some of which like "Number of players" is not exposed properly. But I'll get that added.

**Comment by davort** [comment]
@dan13ram 
> all of this info is already available and exposed :D

Even things like `creator` and `date created` ?

**Comment by dan13ram** [comment]
> Even things like `creator` and `date created` ?

@davort  Yes. Its available and exposed by the subgraph. Just not displayed on the UI.

**Comment by davort** [comment]
Gotcha. Seems like I misinterpreted the phrase "expose", since I am approaching this from the UI end. 
Will correct the issue description, to make it perfectly clear what I meant and what needs doing 👍

**Comment by davort** [comment]
### Re: Number of players

@dan13ram @vidvidvid 
A question re: "Number of players" → What of the following does this number represent:
1. Total number of players that have started playing the QC
2. Number of players that are currently playing the QC = started, but haven't yet finished?
3. Something else?

_(Whichever of the above is correct, we'd probably wanna show a tooltip for this label, in which we clarify what the number represents.)_

And a random thought: might it be interesting to show how many players have actually finished the QC, as opposed to how many have started?

**Comment by vidvidvid** [comment]
We can display both numbers as little tags. We can make the tag for # of players who have finished look more premium. What do you think?

**Comment by dan13ram** [comment]
@davort I understood it as "total number of players that have attempted at least one quest" which includes ones that have completed it.

We def could have another stat for total players who have completed the quest chain. I really like that idea 👌🏽
